### ISSUE TITLE
Run fails with undefined error for missconfigured profile

### ISSUE THREAD

**Issue by freaz** [superfaceai/testing#15]
`targetedProfileProvider` can be undefined 

https://github.com/superfaceai/testing/blob/dev/src/superface-test.utils.ts#L112

## Expected Behavior
It should handle situation when profile configuration for given provider doesn't exists.

## Current Behavior
Throws TypeError:

```
TypeError: Cannot use 'in' operator to search for 'file' in undefined

      at isProfileProviderLocal (../node_modules/@superfaceai/testing/src/superface-test.utils.ts:115:13)
      at SuperfaceTest.<anonymous> (../node_modules/@superfaceai/testing/src/superface-test.ts:237:36)
      at step (../node_modules/@superfaceai/testing/dist/superface-test.js:33:23)
      at Object.next (../node_modules/@superfaceai/testing/dist/superface-test.js:14:53)
      at ../node_modules/@superfaceai/testing/dist/superface-test.js:8:71
      at Object.<anonymous>.__awaiter (../node_modules/@superfaceai/testing/dist/superface-test.js:4:12)
      at SuperfaceTest.Object.<anonymous>.SuperfaceTest.checkForMapInSuperJson (../node_modules/@superfaceai/testing/dist/superface-test.js:198:16)
      at SuperfaceTest.<anonymous> (../node_modules/@superfaceai/testing/src/superface-test.ts:110:22)
      at step (../node_modules/@superfaceai/testing/dist/superface-test.js:33:23)
```

## Possible Solution
Not obligatory, but suggest a fix/reason for the bug

## Steps to Reproduce
Provide a link to a live example, or an unambiguous set of steps to reproduce this bug. Include code to reproduce, if relevant
1. Create project with any profile and provider
2. rename provider in profile configuration to something invalid

## Your Environment
Include as many relevant details about the environment you experienced the bug in. Preferably include:
* Version used: 1.0.0
* Environment name and version (e.g. Node 8) v14.17.3
* Operating System and version MacOS Monterey

**Comment by martinalbert** [comment]
`profileId` that is passed in `isProfileProviderLocal()` is handled [before](https://github.com/superfaceai/testing/blob/b9da1981bbc208b765d12e958fd65d112d2a8145/src/superface-test.ts#L420-L424)

I can't replicate that `TypeError`, I'm getting `SdkExecutionError` when renaming provider or profile in super.json. What profile configuration do you mean?

**Comment by freaz** [comment]
I should capture state I had. It happened when I was renaming provider. I will try to prepare exact reproductin steps in Station.
